import json

import pytest
from helpers import assert_valid_mermaid_er, shop_schema

from diagram_regenerator.model import Column, Schema, Table
from diagram_regenerator.render import (
    MarkdownOptions,
    MermaidOptions,
    format_for_path,
    render,
    render_dbml,
    render_html,
    render_markdown,
    render_mermaid,
)
from diagram_regenerator.render.markdown import anchor, overview_columns
from diagram_regenerator.render.mermaid import attribute_type, entity_id, neighbours


def test_mermaid_is_valid_and_complete():
    text = render_mermaid(shop_schema())
    assert_valid_mermaid_er(text)
    assert "billing__invoices {" in text
    assert "numeric(10_2) balance" in text
    assert "enum kind" in text
    assert "varchar(255) email UK \"Login 'email'\"" in text
    assert "bigint order_id PK, FK" in text
    assert "note___pipe" in text


def test_mermaid_relationship_cardinality():
    text = render_mermaid(shop_schema())
    # required FK: exactly one parent; optional FK: zero or one parent
    assert 'customers ||..o{ orders : "customer_id"' in text
    # FK inside the child PK is identifying (solid line)
    assert 'orders ||--o{ order_items : "order_id"' in text
    # unique FK column is one-to-one, nullable side is optional
    assert 'orders |o..o| billing__invoices : "order_id"' in text
    # self reference
    assert 'billing__invoices |o..o{ billing__invoices : "parent_id"' in text


def test_mermaid_column_modes_and_layout():
    keys = render_mermaid(shop_schema(), MermaidOptions(columns="keys", layout="elk"))
    assert_valid_mermaid_er(keys)
    assert keys.startswith("---\nconfig:\n  layout: elk\n---\nerDiagram")
    assert "balance" not in keys and "email" in keys
    none = render_mermaid(shop_schema(), MermaidOptions(columns="none"))
    assert_valid_mermaid_er(none)
    assert "{" not in none.replace("o{", "")
    with pytest.raises(ValueError):
        MermaidOptions(columns="some")


def test_mermaid_focus_with_stubs():
    schema = shop_schema()
    assert neighbours(schema, ["orders"]) == {"customers", "order_items", "billing.invoices"}
    text = render_mermaid(schema, tables=["orders"], stubs=neighbours(schema, ["orders"]))
    assert_valid_mermaid_er(text)
    assert "    customers\n" in text and "customers {" not in text
    assert 'orders ||--o{ order_items : "order_id"' in text


def test_mermaid_sanitisers():
    assert entity_id("billing.invoices") == "billing__invoices"
    assert entity_id("2fa codes") == "_2fa_codes"
    assert attribute_type("integer unsigned") == "integer_unsigned"
    assert attribute_type("timestamp(3)") == "timestamp(3)"
    assert attribute_type("text[]") == "text[]"


def test_markdown_document():
    text = render_markdown(shop_schema(), MarkdownOptions(source="db/migrations"))
    assert text.startswith("<!-- Generated by diagram-regenerator")
    assert "**4 tables · 15 columns** · source `db/migrations`" in text
    assert "```mermaid\nerDiagram" in text
    assert "[billing.invoices](#billinginvoices)" in text
    assert '| `email` | `varchar(255)` |  |  | UK | Login "email" |' in text
    assert "_draft:_ Soft-delete time." in text
    assert "`note \\| pipe`" in text
    assert "FK → [customers](#customers).`id` (cascade on delete)" in text
    assert "**Referenced by:** [orders](#orders).`customer_id`" in text
    assert "**Indexes:** `ix_orders_status` (`status`)" in text
    assert "| `mood` | `sad`, `ok` |" in text
    # deterministic: same input, same bytes
    assert text == render_markdown(shop_schema(), MarkdownOptions(source="db/migrations"))


def test_markdown_groups_and_large_schemas():
    schema = shop_schema()
    text = render_markdown(
        schema, MarkdownOptions(groups={"Billing": ["billing.*"], "Empty": ["x*"]})
    )
    assert "### Billing" in text and "### Empty" not in text
    assert "  - [Billing](#billing)" in text
    assert overview_columns(10, "auto") == "all"
    assert overview_columns(40, "auto") == "keys"
    assert overview_columns(200, "auto") == "none"
    assert overview_columns(200, "all") == "all"
    big = Schema()
    for i in range(30):
        big.add_table(
            Table(
                f"t{i}",
                columns=[Column("id", "int", nullable=False), Column("v", "int")],
                primary_key=["id"],
            )
        )
    assert "key columns only" in render_markdown(big)


def test_markdown_empty_schema():
    assert "_The schema has no tables yet._" in render_markdown(Schema())


def test_anchor_matches_github():
    assert anchor("billing.invoices") == "billinginvoices"
    assert anchor("Order Items") == "order-items"
    assert anchor("user_accounts") == "user_accounts"


def test_dbml():
    text = render_dbml(shop_schema())
    assert "Enum mood {\n  sad\n  ok\n}" in text
    assert "Table customers [note: 'People who buy things.'] {" in text
    assert "  id bigint [pk, increment]" in text
    assert "  email varchar(255) [not null, unique, note: 'Login \"email\"']" in text
    assert "  balance numeric(10,2) [default: 0]" in text
    assert "  status text [default: 'new']" in text
    assert '  "note | pipe" text' in text
    assert "Table billing.invoices {" in text
    assert "    (order_id, line) [pk]" in text
    assert "Ref: orders.customer_id > customers.id [delete: cascade]" in text
    assert "Ref: billing.invoices.order_id - orders.id" in text


def test_html_is_self_contained_and_escaped():
    schema = shop_schema()
    schema.tables["customers"].comment = "<script>alert(1)</script>"
    page = render_html(schema, title="Shop", source="db")
    assert page.startswith("<!doctype html>")
    assert "&lt;script&gt;alert(1)&lt;/script&gt;" in page
    assert "<script>alert(1)" not in page
    payload = page.split('<script type="application/json" id="diagrams">')[1].split("</script>")[0]
    data = json.loads(payload)
    assert set(data["focus"]) == set(schema.tables)
    assert_valid_mermaid_er(data["overview"])
    for diagram in data["focus"].values():
        assert_valid_mermaid_er(diagram)


def test_render_dispatch_and_format_detection():
    schema = shop_schema()
    assert render(schema, "json") == schema.to_json()
    assert render(schema, "mmd").startswith("erDiagram")
    assert render(schema, "md").startswith("<!--")
    assert format_for_path("docs/SCHEMA.md") == "markdown"
    assert format_for_path("schema/schema.json") == "json"
    assert format_for_path("x.dbml") == "dbml"
    with pytest.raises(ValueError):
        format_for_path("x.png")
    with pytest.raises(ValueError):
        render(schema, "png")
