"""The schema docs page: Mermaid diagram(s) plus a data dictionary.

Output is deterministic (no timestamps), so the committed file changes only
when the schema or its descriptions do, and its git history doubles as a
changelog of the database.
"""

from __future__ import annotations

import fnmatch
import re
from dataclasses import dataclass, field

from diagram_regenerator.model import DRAFT_PREFIX, Column, Schema, Table
from diagram_regenerator.render.mermaid import (
    MermaidOptions,
    neighbours,
    render_mermaid,
)

GENERATED_MARKER = "<!-- Generated by diagram-regenerator. Edit descriptions, not this file. -->"


@dataclass
class MarkdownOptions:
    title: str = "Database schema"
    source: str | None = None
    diagram: str = "auto"  # auto | all | keys | none (columns shown in the overview)
    comments_in_diagram: bool = True
    layout: str | None = None
    groups: dict[str, list[str]] = field(default_factory=dict)
    regenerate_hint: str = "diagram-regen generate"


def overview_columns(table_count: int, mode: str) -> str:
    """Pick how much to draw so large schemas stay legible."""
    if mode != "auto":
        return mode
    if table_count <= 25:
        return "all"
    if table_count <= 60:
        return "keys"
    return "none"


def anchor(text: str) -> str:
    """GitHub's heading anchor algorithm (lower-case, punctuation dropped)."""
    slug = text.strip().lower()
    slug = re.sub(r"[^\w\- ]", "", slug)
    return slug.replace(" ", "-")


def cell(text: object) -> str:
    return str(text).replace("|", "\\|").replace("\n", " ").strip()


def describe(text: str | None) -> str:
    if not text:
        return ""
    text = text.strip()
    if text.lower().startswith(DRAFT_PREFIX):
        return "_draft:_ " + cell(text[len(DRAFT_PREFIX) :].strip())
    return cell(text)


def group_tables(schema: Schema, groups: dict[str, list[str]]) -> dict[str, list[str]]:
    """Resolve ``{"Billing": ["invoice*", ...]}`` globs to table keys."""
    resolved: dict[str, list[str]] = {}
    for name, patterns in groups.items():
        keys = [
            key
            for key, table in sorted(schema.tables.items())
            if any(
                fnmatch.fnmatchcase(key, p) or fnmatch.fnmatchcase(table.name, p) for p in patterns
            )
        ]
        if keys:
            resolved[name] = keys
    return resolved


def render_markdown(schema: Schema, options: MarkdownOptions | None = None) -> str:
    options = options or MarkdownOptions()
    tables = schema.sorted_tables()
    out: list[str] = [GENERATED_MARKER, f"# {options.title}", ""]

    stats = f"**{len(tables)} tables · {schema.column_count} columns**"
    if options.source:
        stats += f" · source `{options.source}`"
    stats += f" · fingerprint `{schema.fingerprint()}`"
    out += [stats, ""]
    out += [
        f"> Regenerate with `{options.regenerate_hint}`. Column descriptions come from database "
        "comments and the descriptions file; rows marked _draft_ were suggested automatically "
        "and await review.",
        "",
    ]

    if not tables:
        out += ["_The schema has no tables yet._", ""]
        return "\n".join(out)

    groups = group_tables(schema, options.groups)
    out += ["## Contents", ""]
    out.append("- [Entity-relationship diagram](#entity-relationship-diagram)")
    for name in groups:
        out.append(f"  - [{name}](#{anchor(name)})")
    links = " · ".join(f"[{t.key}](#{anchor(t.key)})" for t in tables)
    out.append(f"- [Tables](#tables): {links}")
    if schema.enums:
        out.append("- [Enums](#enums)")
    out.append("")

    out += ["## Entity-relationship diagram", ""]
    columns = overview_columns(len(tables), options.diagram)
    if columns != "all":
        out += [
            f"_{len(tables)} tables: the overview shows "
            + ("key columns only" if columns == "keys" else "tables and relationships only")
            + ". Every column is listed under [Tables](#tables)._",
            "",
        ]
    mermaid_options = MermaidOptions(
        columns=columns, comments=options.comments_in_diagram, layout=options.layout
    )
    out += ["```mermaid", render_mermaid(schema, mermaid_options).rstrip(), "```", ""]

    for name, keys in groups.items():
        focus = MermaidOptions(
            columns="all", comments=options.comments_in_diagram, layout=options.layout
        )
        diagram = render_mermaid(schema, focus, tables=keys, stubs=neighbours(schema, keys))
        out += [f"### {name}", "", "```mermaid", diagram.rstrip(), "```", ""]

    out += ["## Tables", ""]
    for table in tables:
        out += _table_section(schema, table)

    if schema.enums:
        out += ["## Enums", "", "| Enum | Values |", "| --- | --- |"]
        for name in sorted(schema.enums):
            values = ", ".join(f"`{cell(v)}`" for v in schema.enums[name])
            out.append(f"| `{cell(name)}` | {values} |")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def _table_section(schema: Schema, table: Table) -> list[str]:
    out = [f"### {table.key}", ""]
    if table.comment:
        out += [describe(table.comment), ""]
    out += [
        "| Column | Type | Nullable | Default | Keys | Description |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for column in table.columns:
        out.append(
            "| "
            + " | ".join(
                [
                    f"`{cell(column.name)}`",
                    f"`{cell(column.type)}`",
                    "yes" if column.nullable else "",
                    _default(column),
                    _keys(schema, table, column),
                    describe(column.comment),
                ]
            )
            + " |"
        )
    out.append("")

    if table.indexes:
        parts = []
        for index in table.indexes:
            columns = ", ".join(f"`{cell(c)}`" for c in index.columns)
            label = "unique " if index.unique else ""
            name = f"`{cell(index.name)}` " if index.name else ""
            parts.append(f"{label}{name}({columns})")
        out += ["**Indexes:** " + " · ".join(parts), ""]

    referenced = schema.referencing(table.key)
    if referenced:
        parts = [
            f"[{other.key}](#{anchor(other.key)}).`{', '.join(fk.columns)}`"
            for other, fk in referenced
        ]
        out += ["**Referenced by:** " + " · ".join(parts), ""]
    return out


def _default(column: Column) -> str:
    if column.autoincrement:
        return "auto-increment"
    return f"`{cell(column.default)}`" if column.default is not None else ""


def _keys(schema: Schema, table: Table, column: Column) -> str:
    keys = []
    if column.name in table.primary_key:
        keys.append("PK")
    fk = table.foreign_key_for(column.name)
    if fk:
        position = fk.columns.index(column.name)
        ref_column = fk.ref_columns[position] if position < len(fk.ref_columns) else "?"
        target = (
            f"[{fk.ref_table}](#{anchor(fk.ref_table)})"
            if fk.ref_table in schema.tables
            else f"`{fk.ref_table}`"
        )
        action = f" ({fk.on_delete.lower()} on delete)" if fk.on_delete else ""
        keys.append(f"FK → {target}.`{cell(ref_column)}`{action}")
    if column.name not in table.primary_key and table.is_unique([column.name]):
        keys.append("UK")
    return "<br>".join(keys)
