"""Rebuild the open-source demos: fetch pinned migrations, generate docs and diffs.

    python examples/oss/build.py            # fetch (cached) + regenerate everything
    python examples/oss/build.py umami      # just one app

Only each app's migrations folder is downloaded (sparse, blob-filtered
clone at a pinned commit) into examples/oss/.cache, which git ignores. For
every app this writes, next to its diagram-regen.toml:

* README.md            the generated diagram + data dictionary
* schema.json          the snapshot
* latest-migration.md  the PR comment the app's newest migration would get
"""

from __future__ import annotations

import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

from diagram_regenerator.config import load_config
from diagram_regenerator.diff import diff_schemas
from diagram_regenerator.project import Project
from diagram_regenerator.report import format_markdown
from diagram_regenerator.sources.sql import migration_order, replay

HERE = Path(__file__).resolve().parent
CACHE = HERE / ".cache"


@dataclass(frozen=True)
class App:
    name: str
    repo: str
    commit: str
    path: str

    @property
    def checkout(self) -> Path:
        return CACHE / self.name

    @property
    def migrations(self) -> Path:
        return self.checkout / self.path


APPS = [
    App(
        "umami",
        "umami-software/umami",
        "ec0ff50388c264ed8ce46f00967e92f7e71476ae",
        "prisma/migrations",
    ),
    App(
        "atuin",
        "atuinsh/atuin",
        "d440a2e616825533d3eee0db2af7d22d68dcc5c2",
        "crates/atuin-server/src/db/postgres/migrations",
    ),
    App(
        "hoppscotch",
        "hoppscotch/hoppscotch",
        "63273f8e599e73f0fb38c0739314e8d46b6bc83d",
        "packages/hoppscotch-backend/prisma/migrations",
    ),
]


def git(*args: str, cwd: Path) -> str:
    return subprocess.run(
        ["git", *args], cwd=cwd, check=True, capture_output=True, text=True
    ).stdout


def fetch(app: App) -> None:
    """Sparse, shallow checkout of just the migrations folder at the pinned commit."""
    target = app.checkout
    if (target / ".git").exists() and git("rev-parse", "HEAD", cwd=target).strip() == app.commit:
        return
    target.mkdir(parents=True, exist_ok=True)
    if not (target / ".git").exists():
        git("init", "-q", cwd=target)
        git("remote", "add", "origin", f"https://github.com/{app.repo}.git", cwd=target)
    git("sparse-checkout", "set", app.path, cwd=target)
    git("fetch", "-q", "--depth", "1", "--filter=blob:none", "origin", app.commit, cwd=target)
    git("checkout", "-q", "--force", "FETCH_HEAD", cwd=target)
    print(f"fetched {app.repo}@{app.commit[:7]} {app.path}")


def build(app: App) -> None:
    folder = HERE / app.name
    project = Project(load_config(folder / "diagram-regen.toml"))
    schema = project.load()
    for output in project.outputs(schema):
        state = "updated" if output.write() else "unchanged"
        print(f"  {state:<9} {output.path.relative_to(HERE.parent.parent)}")

    # The newest migration that changes table structure, as its PR would have shown it
    # (later migrations may only touch functions or data).
    files = migration_order(
        [p.relative_to(app.migrations).as_posix() for p in app.migrations.rglob("*.sql")],
        "postgresql",
    )

    def state(count: int):
        texts = [(n, (app.migrations / n).read_text(encoding="utf-8")) for n in files[:count]]
        return project.filter(replay(texts, "postgresql").schema)

    after = schema
    for count in range(len(files), 0, -1):
        before = state(count - 1)
        diff = diff_schemas(before, after)
        if diff.has_changes:
            break
        after = before
    migration = files[count - 1]
    skipped = len(files) - count
    later = (
        f" ({skipped} later migration{'s' * (skipped != 1)} {'change' if skipped != 1 else 'changes'} no tables)"
        if skipped
        else ""
    )
    footer = (
        f"<sub>Generated by `python examples/oss/build.py` from "
        f"[{app.repo}@{app.commit[:7]}](https://github.com/{app.repo}/tree/{app.commit}/{app.path}): "
        f"the schema before `{migration}` compared with the schema after it{later}.</sub>"
    )
    text = format_markdown(
        diff, title=f"🗺️ {app.name}: what `{migration}` changes", footer=footer, marker=False
    )
    path = folder / "latest-migration.md"
    path.write_text(text, encoding="utf-8")
    print(f"  wrote     {path.relative_to(HERE.parent.parent)} ({diff.summary()})")


def main(argv: list[str]) -> int:
    selected = [app for app in APPS if not argv or app.name in argv]
    for app in selected:
        print(f"{app.name}:")
        fetch(app)
        build(app)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
